# Generated by Django 4.2.7 on 2024-02-20 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='imag',
            new_name='img',
        ),
    ]
